### ISSUE TITLE
Don't call function from package code

### ISSUE THREAD

**Issue by barryrowlingson** [dougaltoms/wetherspoons#1]
Here:
https://github.com/dougaltoms/wetherspoons/blob/c1e52692e036a09d5dc81bf92ebcc80397ce9c9d/R/PaletteCode.R#L52

you call the function you just defined - that's probably not a good idea since it will run on package load, which is generally a bad thing for packages...

**Comment by dougaltoms** [comment]
Good spot - that should have been removed previously. Now resolved, thanks!
